import {
  FloorLevel,
  type GameState,
  type LogEntry,
  type Msg,
} from '../src/core/types';

export function makeGameState(overrides: Partial<GameState> = {}): GameState {
  const clock = overrides.clock ?? { hour: 8, minute: 0, totalMinutes: 0 };
  return {
    tick: 0,
    time: 0,
    clock,
    samosborActive: false,
    samosborTimer: 120,
    samosborCount: 0,
    paused: false,
    gameOver: false,
    showInventory: false,
    mapMode: 0,
    showQuests: false,
    invSel: 0,
    msgs: [] as Msg[],
    quests: [],
    nextQuestId: 1,
    currentFloor: FloorLevel.LIVING,
    fogSpreadTimer: 0,
    showMenu: false,
    menuSel: 0,
    showNpcMenu: false,
    npcMenuSel: 0,
    npcMenuTarget: -1,
    npcMenuTab: 'main',
    npcTalkText: '',
    questPage: 0,
    tradeCursorX: 0,
    tradeCursorY: 0,
    tradeSide: 'npc',
    showContainerMenu: false,
    containerMenuTarget: -1,
    containerCursorX: 0,
    containerCursorY: 0,
    containerSide: 'container',
    showDebug: false,
    debugSel: 0,
    showFactions: false,
    showLog: false,
    logScroll: 0,
    msgLog: [] as LogEntry[],
    dmgFlash: 0,
    dmgSeed: 0,
    deathTimer: 0,
    sleeping: false,
    beamFx: 0,
    beamAngle: 0,
    beamLen: 0,
    uvBeamFx: 0,
    uvBeamLen: 0,
    gameWon: false,
    ...overrides,
  };
}
