import * as fs from 'fs';
import * as path from 'path';

const prototypeSrc = fs.readFileSync('scripts/markov_core_prototype.ts', 'utf8');
const compilerSrc = fs.readFileSync('scripts/compile_markov_matrix.ts', 'utf8');

// Extract MarkovModel class and related interfaces from prototype
const modelRegex = /const START_TOKEN = "<s>";[\s\S]*?public generate\(/;
const match = prototypeSrc.match(modelRegex);
if (!match) throw new Error('Could not find MarkovModel in prototype');

let modelCode = match[0].replace('public generate(', '// public generate omitted');
// We need to keep the closing brace for MarkovModel
const graphToBuildHeuristics = /const START_TOKEN[\s\S]*?public buildHeuristics.*?}[\s\S]*?\n  }/;
const match2 = prototypeSrc.match(graphToBuildHeuristics);
if (!match2) throw new Error('Could not extract MarkovModel class fully');
modelCode = match2[0] + '\n}\n';

// Corpus loading from prototype
const corpusLoaderRegex = /const RAW_CORPUS[\s\S]*?\} catch \(e\) \{[\s\S]*?\n\}/;
const corpusMatch = prototypeSrc.match(corpusLoaderRegex);
if (!corpusMatch) throw new Error('Could not find corpus loader in prototype');
let corpusLoaderCode = corpusMatch[0];
// Update categoryMap regex to use CANONICAL_CATEGORIES keys instead of <СУБЪЕКТ>
corpusLoaderCode = corpusLoaderCode.replace(/'<СУБЪЕКТ>'/g, "'<SUBJ>'");
corpusLoaderCode = corpusLoaderCode.replace(/'<МЕСТО>'/g, "'<PLACE>'");
corpusLoaderCode = corpusLoaderCode.replace(/'<УГРОЗА>'/g, "'<THREAT>'");
corpusLoaderCode = corpusLoaderCode.replace(/'<ЦЕННЫЙ_ПРЕДМЕТ>'/g, "'<ITEM>'");
corpusLoaderCode = corpusLoaderCode.replace(/'<ФРАКЦИЯ>'/g, "'<FACTION>'");
// also fix the final regex replacements
corpusLoaderCode = corpusLoaderCode.replace(/<СУБЪЕКТ>/g, "<SUBJ>");
corpusLoaderCode = corpusLoaderCode.replace(/<МЕСТО>/g, "<PLACE>");
corpusLoaderCode = corpusLoaderCode.replace(/<УГРОЗА>/g, "<THREAT>");
corpusLoaderCode = corpusLoaderCode.replace(/<ЦЕННЫЙ_ПРЕДМЕТ>/g, "<ITEM>");
corpusLoaderCode = corpusLoaderCode.replace(/<ФРАКЦИЯ>/g, "<FACTION>");


// Now replace the compileAndVerify function in compile_markov_matrix.ts
const replacementCompileAndVerify = `
interface CorpusItem {
  text: string;
  tags: string[];
}

${modelCode}

${corpusLoaderCode}

function compileAndVerify(): void {
  // Sanity verify all entries against ALIEN_FRANCHISE_BLACKLIST
  for (const [catName, items] of Object.entries(CANONICAL_CATEGORIES)) {
    for (const item of items) {
      if (!isSanitizedWord(item.text)) {
        throw new Error(\`Sanitization check failed for item in \${catName}: \${item.text}\`);
      }
    }
  }

  console.log('[Compile Markov Matrix] Training Markov Model...');
  const model = new MarkovModel(2);
  model.train(RAW_CORPUS);

  console.log('[Compile Markov Matrix] Building heuristics...');
  const targetTags = Object.keys(CANONICAL_CATEGORIES).map(k => \`<\${k}>\`);
  model.buildHeuristics(targetTags);

  console.log('[Compile Markov Matrix] Serializing graph...');
  const objGraph: any = {};
  for (const [hist, trans] of model.graph.entries()) {
    objGraph[hist] = {};
    for (const [next, info] of trans.entries()) {
      objGraph[hist][next] = { count: info.count, tags: info.tags };
    }
  }

  const objDistances: any = {};
  // patternDistances is private, let's cast to any
  const dists = (model as any).patternDistances;
  for (const [target, distMap] of dists.entries()) {
    objDistances[target] = Object.fromEntries(distMap.entries());
  }

  const outPath = path.resolve(__dirname, '../src/data/markov_compiled_matrix.ts');
  const fileContent = \`/* ── Precompiled Markov Matrix & Categories (Build-Time Generated) ── */
/* Do not edit manually. Generated by scripts/compile_markov_matrix.ts */
/* Contains 100% canonical Gigahrush & Samosbor entities with PCA axes. */

export interface CompiledCategoryItem {
  readonly text: string;
  readonly weight: number;
  readonly tags: readonly string[];
}

export interface CompiledSyntaxSkeleton {
  readonly id: string;
  readonly pattern: readonly string[];
  readonly intent: string;
  readonly weight: number;
}

export const COMPILED_CATEGORIES: Readonly<Record<string, readonly CompiledCategoryItem[]>> = \${JSON.stringify(CANONICAL_CATEGORIES, null, 2)} as const;

export const COMPILED_SKELETONS: readonly CompiledSyntaxSkeleton[] = \${JSON.stringify(CANONICAL_SKELETONS, null, 2)} as const;

export const COMPILED_MARKOV_GRAPH: Record<string, Record<string, { count: number, tags: Record<string, number> }>> = \${JSON.stringify(objGraph)};
export const COMPILED_PATTERN_DISTANCES: Record<string, Record<string, number>> = \${JSON.stringify(objDistances)};
\`;

  fs.writeFileSync(outPath, fileContent, 'utf-8');
  console.log(\`[Compile Markov Matrix] Successfully wrote \${outPath} (\${(fileContent.length / 1024 / 1024).toFixed(2)} MB)\`);
}

compileAndVerify();
`;

const oldCompileFuncRegex = /function compileAndVerify\(\)[\s\S]*$/;
const newCompilerSrc = compilerSrc.replace(oldCompileFuncRegex, replacementCompileAndVerify);

fs.writeFileSync('scripts/compile_markov_matrix.ts', newCompilerSrc, 'utf8');
