/* Generated by scripts/generate-viewmodel-sprites.mjs. Do not edit manually. */

const IDS: readonly string[] = [];

/** Идентификаторы вида `<itemId>:<frame>`, запечённые из `viewmodels/`. */
export const GENERATED_VIEWMODEL_FRAME_IDS: readonly string[] = IDS;

/** RLE-пары `[count, value, ...]` на кадр. Разжимаются только при промахе кэша. */
const GENERATED_VIEWMODEL_RLE: Record<string, readonly number[]> = {};

/** Сторона запечённого кадра. Совпадает с `VM` и проверяется тестом. */
export const GENERATED_VIEWMODEL_SIDE = 128;

export function getGeneratedViewmodelFrame(id: string | undefined): Uint32Array | undefined {
  if (!id) return undefined;
  const rle = GENERATED_VIEWMODEL_RLE[id];
  if (!rle) return undefined;
  const out = new Uint32Array(GENERATED_VIEWMODEL_SIDE * GENERATED_VIEWMODEL_SIDE);
  let p = 0;
  for (let i = 0; i < rle.length; i += 2) {
    const count = rle[i];
    const value = rle[i + 1] >>> 0;
    for (let k = 0; k < count && p < out.length; k++) out[p++] = value;
  }
  return p === out.length ? out : undefined;
}
